add check for git changes

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -1,5 +1,5 @@
-name: build-release
 
+name: build-release
 on:
   push:
     branches: [ "main" ]
@@ -34,6 +34,13 @@ jobs:
     - uses: actions/checkout@v4
     - name: build
       run: cargo build --release
+    - name: check for any changes in the git tree
+      run: |
+        if [[ -n "$(git status --porcelain)" ]]; then
+          echo '::error title=post-build check::changes detected in git tree'
+          git status
+          exit 1
+        fi
     - name: Attest Build Provenance
       uses: actions/attest-build-provenance@v1
       with:
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -16,6 +16,13 @@ jobs:
     - uses: actions/checkout@v4
     - name: cargo build
       run: scripts/cargo_to_gh rustc --message-format json -- -Awarnings
+    - name: check for any changes in the git tree
+      run: |
+        if [[ -n "$(git status --porcelain)" ]]; then
+          echo '::error title=post-build check::changes detected in git tree'
+          git status
+          exit 1
+        fi
 
   check:
     runs-on: ubuntu-latest
