upload artifacts

diff --git a/.github/workflows/prepare-new-release.yml b/.github/workflows/prepare-new-release.yml
--- a/.github/workflows/prepare-new-release.yml
+++ b/.github/workflows/prepare-new-release.yml
@@ -31,6 +31,40 @@ jobs:
       with:
         ref: ${{ github.event.inputs.base_ref }}
 
+    - name: Prepare random dir
+      id: random-dir
+      run: echo "path=$(mktemp -d)" >> "$GITHUB_OUTPUT"
+
+    - name: Find latest build
+      id: latest-build
+      run: |
+        set -euo pipefail
+        run_info="$(gh run list -b "$RUN_REF" -w build-release.yml --limit 1 --json status,conclusion,databaseId)"
+        run_id="$(echo "$run_info" | jq -re '.[].databaseId' )"
+
+        if [[ "$(echo "$run_info" | jq -r '.[].conclusion')" != success ]]; then
+          echo "::error ::Found run $run_id but its conclusion was $(echo "$run_info" | jq '.[].conclusion')"
+          exit 1
+        fi
+        run: echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
+      env:
+        RUN_REF: ${{ github.event.inputs.base_ref }}
+
+    - name: Download build artifacts
+      run: gh run download "$RUN_ID" -p 'mdq-*' --dir "$TMP_DIR"
+      env:
+        TMP_DIR: ${{ steps.random-dir.outputs.path }}
+        RUN_ID: ${{ steps.latest-build.outputs.run_id }}
+
+    - name: Re-zip build artifacts
+      run: |
+        set -euo pipefail
+        for artifact_name in $(ls -1) ; do
+          zip "${artifact_name}.zip" "$artifact_name"/*
+          rm -rf "$artifact_name"/
+        done
+      working-directory: ${{ steps.random-dir.outputs.path }}
+
     - name: Set up Rust
       uses: actions-rs/toolchain@v1
       with:
@@ -49,8 +83,16 @@ jobs:
     - name: Create new release
       id: create_release
       run: |
-        release_url="$(gh release create "v${{ github.event.inputs.new_version }}" --draft --title "v${{ github.event.inputs.new_version }}" --generate-notes)"
+        release_url="$(gh release create "v${{ github.event.inputs.new_version }}" --draft --title "v${{ github.event.inputs.new_version }}" --generate-notes --target "$TARGET_REF")"
         echo "release_url=$release_url" >> "$GITHUB_OUTPUT"
+      env:
+        TARGET_REF: ${{ github.event.inputs.base_ref }}
+
+    - name: Upload artifacts
+      run: gh release upload "$RELEASE_TAG" "$TMP_DIR"/*
+      env:
+        TMP_DIR: ${{ steps.random-dir.outputs.path }}
+        RELEASE_TAG: "v${{ github.event.inputs.new_version }}"
 
     - name: Update Cargo.toml
       run: sed -i 's/^version = ".*"/version = "${{ github.event.inputs.new_version }}"/' Cargo.toml
@@ -70,4 +112,6 @@ jobs:
 
     - name: Create Pull Request
       run: |
-        gh pr create --title "Prepare v${{ github.event.inputs.new_version }}" --body "Bump version to ${{ github.event.inputs.new_version }}" --base "${{ github.event.inputs.base_ref }}"
+        gh pr create --title "Prepare v${{ github.event.inputs.new_version }}" --body "Bump version to ${{ github.event.inputs.new_version }}" --base "$TARGET_REF"
+      env:
+        TARGET_REF: ${{ github.event.inputs.base_ref }}
