add task check

diff --git a/.github/workflows/release-publish.yml b/.github/workflows/release-publish.yml
--- a/.github/workflows/release-publish.yml
+++ b/.github/workflows/release-publish.yml
@@ -8,6 +8,7 @@ on:
         required: true
 
 env:
+  RELEASE_VERSION: ${{ inputs.version }}
   BRANCH_NAME: "pending-releases/${{ inputs.version }}"
 
 jobs:
@@ -25,6 +26,7 @@ jobs:
           echo "json=$pr_json" >> "$GITHUB_OUTPUT"
         env:
           REPO_NAME: ${{ github.repository }}
+
       - name: Validate PR status
         run: |
           set -euo pipefail
@@ -35,3 +37,17 @@ jobs:
           fi
         env:
           PR_JSON: ${{ steps.pr-info.outputs.json }}
+
+      - name: Docker pull
+        run: docker pull "yshavit/mdq:${RELEASE_VERSION}-rc"
+
+      - name: Look for unfinished checkbox items
+        run: |
+          exit_status=0
+          while read -r line ; do
+            echo "::error title=unfinished task::$line"
+            exit_status=1
+          done <<<"$(
+            echo "$PR_JSON" | jq -r .body | docker run --rm -i "yshavit/mdq:${RELEASE_VERSION}-rc" '- [ ]' | grep -v '^ *-* *$'
+          )"
+          exit "$exit_status"
