mark various things pub(crate)
Change various items from `pub` to `pub(crate)`. These items weren't
actually public, since their modules weren't exported as pub. This
doesn't change that, but it makes it clearer in the code.

Also add a CI check (and a helper script) to ensure that I'll maintain
this practice going forward.

Resolves #383

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -83,3 +83,35 @@ jobs:
       - uses: actions/checkout@v4
       - name: cargo fmt
         run: cargo fmt --check
+
+  vis-keywords:
+    needs: build
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: check file
+        run: file scripts/flatten-rustdoc-json
+
+      - name: cargo docs (public only)
+        run: cargo +nightly rustdoc --lib -- -Zunstable-options --output-format json
+
+      - name: flatten rustdoc json (public only)
+        run: scripts/flatten-rustdoc-json > target/items-public-only.txt
+
+      - name: cargo docs (all)
+        run: cargo +nightly rustdoc --lib -- -Zunstable-options --output-format json --document-private-items
+
+      - name: flatten rustdoc json (all)
+        run: IGNORE_ITEMS='enum mdq::query::pest::Rule' scripts/flatten-rustdoc-json > target/items-all.txt
+
+      - name: compare
+        run: |
+          if diff -y --suppress-common-lines target/items-public-only.txt target/items-all.txt; then
+            echo "::notice title=pub-vis::all pub items are actually public"
+          else
+            echo "::error title=pub-vis::some items marked pub are not actually public"
+            exit 1
+          fi
