fix `--version`
- add a check that `cargo build` doesn't result in a dirty git tree;
this ensures that `Cargo.toml` and `Cargo.lock` are in sync
- fix the `Cargo.lock`, which will in turn fix `--version`

Resolves #222

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -16,7 +16,17 @@ jobs:
     - uses: actions/checkout@v4
     - name: cargo build
       run: scripts/cargo_to_gh rustc --message-format json -- -Awarnings
-
+    - name: check for any changes in the git tree
+      run: |
+        exit_code=0
+        while read -r status_code file_path; do
+          if [[ -z "$status_code" ]]; then
+            continue
+          fi
+          exit_code=1
+          echo "::error file=$file_path,title=git-status::<$status_code> $file_path"
+        done <<<"$(git status --porcelain)"
+        exit "$exit_code"
   check:
     runs-on: ubuntu-latest
     needs: build
